kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: my_ns
  name: my_ns-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "services", "nodes"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my_ns-reader-access
  namespace: my_ns
subjects:
  - kind: User
    name: krol # Name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: my_ns-reader
  apiGroup: rbac.authorization.k8s.io
