apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: my_user-csr
spec:
  groups:
    - system:authenticated

  usages:
    - digital signature
    - key encipherment
    - server auth

  request: <REPLACE_REQ_BASE64>
